services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3000:8080"
    environment:
      - OPENAI_API_KEY=<sk-YOUR OPENAI API KEY>
    volumes:
      - open-webui:/app/backend/data
    restart: always
    networks:
      - docker-net
volumes:
  open-webui:
networks:
  docker-net:
    driver: bridge
    external: true
