version: '3'
services:
  app: 
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx
    restart: always
    ports:
      # These ports are in format <host-port>:<container-port>
      - 0.0.0.0:80:80 # Public HTTP Port
      - 0.0.0.0:443:443 # Public HTTPS Port
      - 0.0.0.0:81:81 # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP

    # Uncomment the next line if you uncomment anything in the section
    environment:
      # Uncomment this if you want to change the location of 
      # the SQLite DB file within the container
      DB_SQLITE_FILE: "/data/database.sqlite"
      # Uncomment this if IPv6 is not enabled on your host
      DISABLE_IPV6: 'true'
      PUID: 1000
      PGID: 1000
    volumes:
      - /root/dockers/nginx/data:/data
      - /root/dockers/nginx/letsencrypt:/etc/letsencrypt
      - /root/dockers/nginx/html:/usr/share/nginx/html/
      - /root/dockers/nginx/config:/config/
      - /root/dockers/nginx/certbot/cli.ini:/opt/certbot/lib/python3./opt/certbot/lib/python3.11/site-packages/certbot/tests/testdata/cli.ini  # Mount custom cli.ini
    networks:
      - docker-net
networks:
  docker-net:
    driver: bridge
    external: true
